version: '3.2'

services:
  database:
    image: mysql:5.7
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=project
    volumes:
    - database:/var/lib/mysql

  http:
    image: nginx
    depends_on:
    - php
    volumes:
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    - ./:/srv/:ro
    ports:
    - "8087:8087"
  php:
    working_dir: /srv
    volumes:
    - ./:/srv/
volumes:
  database: ~
  esdata:   ~
