presidents:
  type:     rest
  resource: App\Controller\PresidentController

laws:
  type:     rest
  resource: App\Controller\LawController

person:
  type:     rest
  resource: App\Controller\PersonController

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }